language: python

sudo: required
dist: trusty
python: "3.4"

before_install:
  - sudo apt-get update

install:
  - sudo apt-get install clang libclang-3.4-dev -y
  - pip3 install -U --user pip
  - pip3 install -r --user test/requirements.txt

script:
  - pip3 list | grep libclang
  - ./run_test.sh
