language: python

sudo: required
dist: trusty

before_install:
  - sudo apt-get update

install:
  - sudo apt-get install python3
  - sudo apt-get install python3-pip -y
  - sudo apt-get install clang libclang-3.4-dev -y
  - sudo pip3 install -U pip
  - sudo pip3 install neovim libclang-py3==3.4.0
  - export PYTHONPATH=$PYTHONPATH:/usr/lib/python3/dist-packages:/usr/local/lib/python3.4/dist-packages

script:
  - ./run_test.sh
