language: python

sudo: required
os: linux
dist: trusty
python: "2.7"

before_install:
  - sudo apt-get update

install:
  - sudo apt-get install clang cmake libclang-3.4-dev python-clang-3.4 -y
  - sudo pip2 install clang==3.4.0
  - sudo pip2 install -U pip
  - sudo pip2 install -r test/requirements.txt

script:
  - sudo ./run_test.sh
