language: python

sudo: required
dist: trusty
python: "3.4"

before_install:
  - sudo apt-get update

install:
  - sudo apt-get install clang libclang-3.4-dev -y
  - sudo pip3 install -U pip
  - sudo install -r test/requirements.txt

script:
  - pip3 list | grep libclang
  - ./run_test.sh
