language: python

addons:
  apt:
    packages:
      - build-essential
      - swig3.0
      - python3-dev
      - python3-pip

os: linux

python:
  - "3.5"

before_install:
  # Install a supported cmake version (>= 3.4.3)
  - wget -O cmake.sh https://cmake.org/files/v3.10/cmake-3.10.0-rc1-Linux-x86_64.sh
  - sudo sh cmake.sh --skip-license --exclude-subdir --prefix=/usr/local
  # - sudo add-apt-repository ppa:v-launchpad-jochen-sprickerhof-de/pcl -y
  # - sudo apt-get update -q
  # - sudo apt-get install libpcl-dev -y

install:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - make install
  - cd ..

script:
  - cd build
