language: python

addons:
  apt:
    sources:
      - george-edison55-precise-backports

    packages:
      - cmake
      - build-essential
      - clang
      - swig
      - libpython3-dev
      - libpcl-dev
      - libeigen3-dev

os: linux

python:
  - "3.5"

install:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - make install
  - cd ..

script:
  - cd build
  - ./bin/test_clang_completer
  - cd ..
