language: python

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - build-essential
      - g++-7
      - swig3.0
      - python3-dev
      - python3-pip
      - libeigen3-dev
      - gobjc
      - gnustep-devel

os: linux

matrix:
  - dist: bionic
  - dist: xenial
  - dist: trusty

python:
  - "3.5"

before_install:
  # Install a supported cmake version (>= 3.4.3)
  - wget -O cmake.sh https://cmake.org/files/v3.10/cmake-3.10.0-rc1-Linux-x86_64.sh
  - sudo sh cmake.sh --skip-license --exclude-subdir --prefix=/usr/local
  - export CC=gcc-7
  - export CXX=g++-7

install:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - make install
  - cd ..

script:
  - ./build/bin/test_clang_completer
  - ./build/bin/test_token
