language: python

addons:
  apt:
    packages:
      - build-essential
      - clang
      - swig
      - libpython3-dev
      - libpython3.5-dev

os: linux

python:
  - "3.5"

before_install:
  # Install a supported cmake version (>= 3.4.3)
  - wget -O cmake.sh https://cmake.org/files/v3.10/cmake-3.10.0-rc1-Linux-x86_64.sh
  - sudo sh cmake.sh --skip-license --exclude-subdir --prefix=/usr/local

install:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - make install
  - cd ..

script:
  - cd build
