language: python

sudo: required
os: linux
dist: trusty
python: "2.7"

before_install:
  - sudo apt-get update

install:
  - sudo apt-get install clang libclang-3.4-dev python-clang-3.4 -y
  - sudo apt-get install python3-pip
  - sudo pip3 install -U pip
  - sudo pip3 install -r test/requirements.txt

script:
  - sudo ./run_test.sh
