language: python

env:
  - CLANG_VERSION=3.6
  - CLANG_VERSION=3.8
  - CLANG_VERSION=6.0

addons:
  apt:
    packages:
      clang
      libclang-3.6-dev
      libclang-3.8-dev
      libclang-6.0-dev
      cmake

os: linux

python:
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install clang==$CLANG_VERSION

script:
  - python rplugin/python3/deoplete/test_clang_code_completion.py
  - python test/test_cmake_command.py
