language: python

sudo: required
dist: trusty
python: "3.4"

before_install:
  - sudo apt-get update
  - export PYTHONPATH=/usr/lib/python3/dist-packages:/usr/local/lib/python3.4/dist-packages

install:
  - sudo apt-get install clang libclang-3.4-dev -y
  - sudo pip install -U pip
  - sudo pip install -r test/requirements.txt

script:
  - ./run_test.sh
